// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/stockfix-facelift/BoldDark.tsx": () => import("../components/mockups/stockfix-facelift/BoldDark.tsx"),
  "./components/mockups/stockfix-facelift/CleanModern.tsx": () => import("../components/mockups/stockfix-facelift/CleanModern.tsx"),
  "./components/mockups/stockfix-facelift/SharpEnterprise.tsx": () => import("../components/mockups/stockfix-facelift/SharpEnterprise.tsx")
};
